services:
  db:
    container_name: postgres-vault
    image: postgres:latest
    environment:
      POSTGRES_USER: vault-admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5532:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: