name: deploy.yml
on:
  push:
    branches:
      - master

jobs:
  deploy-vault:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run postgresql docker compose file
        run: docker compose up -d
      - name: Wait till docker psql is up
        run: |
          until docker compose exec -T db pg_isready -U vault-admin -d postgres; do
            echo "Waiting on database container"
            sleep 2
          done
      - name: Create database if not existing
        run: |
          docker compose exec -T db psql -U vault-admin -c "CREATE DATABASE vault_db;" || true
      - name: Generate Build Number
        run: |
          BUILD_NUMBER=$(date +'%d%m%Y%H%M%S')
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "Generated Build Number: $BUILD_NUMBER"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - name: Maven Verify
        run: mvn -B -ntp clean verify jib:build -Ddocker.image.tag=$BUILD_NUMBER